version: '3'

services:
  source_db:
    image: postgres:12
    container_name: source_db
    restart: always
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: northwind_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata/source:/var/lib/postgresql/data
      - ./data/northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
    ports:
      - "5432:5432"

  output_db:
    image: postgres:12
    container_name: output_db
    restart: always
    environment:
      POSTGRES_DB: outputdb
      POSTGRES_USER: outputdb_user
      POSTGRES_PASSWORD: thewindisblowing
    volumes:
      - ./dbdata/output:/var/lib/postgresql/data
      - ./data/outputdb.sql:/docker-entrypoint-initdb.d/outputdb.sql
    ports:
      - "5433:5432"
